//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::documents::Entity as Documents;
pub use super::japanese_holiday::Entity as JapaneseHoliday;
pub use super::users::Entity as Users;
pub use super::work_settings::Entity as WorkSettings;
pub use super::work_times::Entity as WorkTimes;
