//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "todo_categories")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub name: Option<String>,
  pub memo: Option<String>,
  pub user_id: i32,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "Entity",
    from = "Column::UserId",
    to = "Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  SelfRef,
}

impl ActiveModelBehavior for ActiveModel {}
